export const OTP_DEMO_CODE = "123456";

export const FLAG_SEVERITY_META = {
  high: { label: "High", color: "#ef4444", bg: "rgba(239,68,68,0.12)" },
  medium: { label: "Medium", color: "#f59e0b", bg: "rgba(245,158,11,0.14)" },
  low: { label: "Low", color: "#4a9fd4", bg: "rgba(74,159,212,0.14)" },
};

export const FLAG_STATUS_META = {
  open: { label: "Open", color: "#ef4444", bg: "rgba(239,68,68,0.1)" },
  reviewed: { label: "Reviewed", color: "#4a9fd4", bg: "rgba(74,159,212,0.12)" },
  escalated: { label: "Escalated", color: "#8b5cf6", bg: "rgba(139,92,246,0.12)" },
  resolved: { label: "Resolved", color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
};

export const AUDIT_RESULT_META = {
  success: { label: "Success", color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
  failed: { label: "Failed", color: "#ef4444", bg: "rgba(239,68,68,0.12)" },
  warning: { label: "Warning", color: "#f59e0b", bg: "rgba(245,158,11,0.14)" },
};

export const ACCOUNT_TRUST_META = {
  trusted: { label: "Trusted", color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
  watchlist: { label: "Watchlist", color: "#f59e0b", bg: "rgba(245,158,11,0.14)" },
  risky: { label: "Risky", color: "#ef4444", bg: "rgba(239,68,68,0.12)" },
};

export const SESSION_STATUS_META = {
  active: { label: "Active", color: "#22c55e", bg: "rgba(34,197,94,0.12)" },
  reverification: { label: "Needs Reverify", color: "#8b5cf6", bg: "rgba(139,92,246,0.12)" },
  logged_out: { label: "Logged Out", color: "#ef4444", bg: "rgba(239,68,68,0.12)" },
};

export const ADMIN_SECURITY_STATE = {
  security_score: 92,
  two_factor: {
    enabled: true,
    method: "OTP step-up",
    last_enabled: "12 Apr 2026",
  },
  last_verification: {
    label: "Approve Payment for ORD-014",
    time: "15 Apr 2026, 09:18",
    method: "OTP step-up",
    status: "verified",
  },
  active_session: {
    device: "Chrome on Windows",
    ip: "36.77.120.45",
    last_login: "15 Apr 2026, 08:41",
  },
  new_device_warning: {
    device_id: "dev-3",
    label: "Safari on iPhone",
    location: "Unknown mobile network",
    ip: "114.5.33.21",
    first_seen: "15 Apr 2026, 09:02",
  },
};

export const ADMIN_TRUSTED_DEVICES = [
  {
    id: "dev-1",
    name: "Chrome on Windows",
    location: "Admin Office",
    ip: "36.77.120.45",
    last_active: "2 min ago",
    status: "trusted",
    trusted_since: "Jan 2026",
  },
  {
    id: "dev-2",
    name: "Edge on Lenovo",
    location: "Warehouse Desk",
    ip: "36.81.220.14",
    last_active: "Yesterday",
    status: "trusted",
    trusted_since: "Mar 2026",
  },
  {
    id: "dev-3",
    name: "Safari on iPhone",
    location: "Unknown mobile network",
    ip: "114.5.33.21",
    last_active: "Just now",
    status: "new",
    trusted_since: "Pending review",
  },
];

export const ADMIN_LOGIN_CONTROL_USERS = [
  {
    id: "USR-201",
    name: "Sara Tancredi",
    email: "sara@gmail.com",
    role: "Customer",
    session_status: "active",
    trust_status: "risky",
    current_device: "Chrome on Android",
    ip_address: "114.5.33.21",
    last_login: "15 Apr 2026, 08:58",
    last_activity: "1 min ago",
    failed_logins_24h: 4,
    activity_snapshot: {
      trust_score: 32,
      orders_24h: 2,
      return_requests_30d: 3,
      new_devices_7d: 2,
    },
    active_flag_ids: ["FLAG-103", "FLAG-104"],
    suspicious_signals: [
      "Shared IP reused by multiple customer accounts",
      "Repeated return requests in the same month",
      "New device detected before payment confirmation",
    ],
    suggestion: "Hold payment or refund approval until device ownership and payment proof are reviewed manually.",
    login_timeline: [
      { label: "Successful login from new Android device", time: "08:58" },
      { label: "Shared IP anomaly linked to multiple accounts", time: "07:49" },
      { label: "Return behavior flag escalated", time: "Yesterday 16:20" },
    ],
  },
  {
    id: "USR-202",
    name: "Maya Sari",
    email: "maya@gmail.com",
    role: "Customer",
    session_status: "active",
    trust_status: "watchlist",
    current_device: "Safari on iPhone",
    ip_address: "36.80.18.90",
    last_login: "15 Apr 2026, 08:25",
    last_activity: "12 min ago",
    failed_logins_24h: 1,
    activity_snapshot: {
      trust_score: 68,
      orders_24h: 1,
      return_requests_30d: 0,
      new_devices_7d: 1,
    },
    active_flag_ids: [],
    suspicious_signals: [
      "First purchase from a brand new device",
      "No long-term purchase history yet",
    ],
    suggestion: "Safe to continue with extra attention to payment proof because the account is still new.",
    login_timeline: [
      { label: "Login success on first known iPhone device", time: "08:25" },
      { label: "Checkout completed with GoPay", time: "08:31" },
    ],
  },
  {
    id: "USR-203",
    name: "Hana Lestari",
    email: "hana@gmail.com",
    role: "Customer",
    session_status: "active",
    trust_status: "trusted",
    current_device: "Chrome on Windows",
    ip_address: "36.71.201.17",
    last_login: "14 Apr 2026, 19:14",
    last_activity: "2 hr ago",
    failed_logins_24h: 0,
    activity_snapshot: {
      trust_score: 89,
      orders_24h: 1,
      return_requests_30d: 0,
      new_devices_7d: 0,
    },
    active_flag_ids: [],
    suspicious_signals: [
      "Known device and stable login pattern",
      "No recent monitoring anomaly",
    ],
    suggestion: "Account looks safe for normal approval flow.",
    login_timeline: [
      { label: "Login success on trusted desktop", time: "Yesterday 19:14" },
      { label: "Order placed with BNI Transfer", time: "Yesterday 19:23" },
    ],
  },
  {
    id: "USR-204",
    name: "Fitri Handayani",
    email: "fitri@gmail.com",
    role: "Customer",
    session_status: "reverification",
    trust_status: "watchlist",
    current_device: "Chrome on MacBook",
    ip_address: "182.1.44.77",
    last_login: "15 Apr 2026, 08:18",
    last_activity: "24 min ago",
    failed_logins_24h: 2,
    activity_snapshot: {
      trust_score: 58,
      orders_24h: 3,
      return_requests_30d: 0,
      new_devices_7d: 1,
    },
    active_flag_ids: ["FLAG-102"],
    suspicious_signals: [
      "Multiple orders created in a short time",
      "Recent login retry before checkout",
    ],
    suggestion: "Ask for re-verification before shipping if more unusual activity appears.",
    login_timeline: [
      { label: "Login retried twice before success", time: "08:18" },
      { label: "Velocity rule triggered after rapid checkout", time: "08:38" },
    ],
  },
  {
    id: "USR-205",
    name: "Admin",
    email: "admin@careofyou.id",
    role: "Admin",
    session_status: "active",
    trust_status: "watchlist",
    current_device: "Chrome on Windows",
    ip_address: "36.77.120.45",
    last_login: "15 Apr 2026, 08:41",
    last_activity: "Just now",
    failed_logins_24h: 5,
    activity_snapshot: {
      trust_score: 74,
      orders_24h: 0,
      return_requests_30d: 0,
      new_devices_7d: 1,
    },
    active_flag_ids: ["FLAG-101", "FLAG-105"],
    suspicious_signals: [
      "Multiple failed admin logins from another IP",
      "Odd-hour login flagged recently",
    ],
    suggestion: "Keep step-up verification enabled and review unknown devices before high-risk actions.",
    login_timeline: [
      { label: "Login success on trusted office device", time: "08:41" },
      { label: "Five failed logins from unknown IP", time: "09:03" },
      { label: "Suspicious login flag opened", time: "09:12" },
    ],
  },
];

export const ADMIN_SENSITIVE_ACTIONS = [
  {
    id: "approve-payment",
    label: "Approve Payment",
    description: "Require step-up verification before payment approval is finalized.",
    audit_action: "payment approved",
    success_message: "Payment approval completed in demo mode.",
  },
  {
    id: "reject-payment",
    label: "Reject Payment",
    description: "Protect payment rejection with an OTP challenge.",
    audit_action: "payment rejected",
    success_message: "Payment rejection completed in demo mode.",
  },
  {
    id: "approve-return",
    label: "Approve Return",
    description: "Review return approval through an extra verification layer.",
    audit_action: "return approved",
    success_message: "Return approval completed in demo mode.",
  },
  {
    id: "resolve-flag",
    label: "Resolve Flag",
    description: "Close a monitoring case only after a step-up confirmation.",
    audit_action: "monitoring flag resolved",
    success_message: "Flag resolution completed in demo mode.",
  },
];

export const ADMIN_MONITORING_FLAGS = [
  {
    id: "FLAG-101",
    rule_code: "LOGIN-FAIL-02",
    severity: "high",
    reason: "Repeated failed login attempts detected from the same IP within 10 minutes.",
    status: "open",
    related_user: "admin@careofyou.id",
    related_order: "-",
    created_at: "15 Apr 2026, 09:12",
    suggested_action: "Confirm the session owner and require step-up verification before more admin actions.",
    timeline: [
      { label: "5 failed login attempts recorded", time: "09:03" },
      { label: "Suspicious login rule triggered", time: "09:08" },
      { label: "Flag opened for admin review", time: "09:12" },
    ],
  },
  {
    id: "FLAG-102",
    rule_code: "ORDER-BURST-01",
    severity: "medium",
    reason: "Multiple orders were placed in a short time from the same account and device fingerprint.",
    status: "reviewed",
    related_user: "fitri@gmail.com",
    related_order: "ORD-018",
    created_at: "15 Apr 2026, 08:46",
    suggested_action: "Review checkout timing and payment proof before moving the order to packing.",
    timeline: [
      { label: "3 orders created in under 7 minutes", time: "08:31" },
      { label: "Velocity rule created a monitoring case", time: "08:38" },
      { label: "Case reviewed by admin", time: "08:46" },
    ],
  },
  {
    id: "FLAG-103",
    rule_code: "IP-SHARE-07",
    severity: "high",
    reason: "Shared IP anomaly detected across multiple customer accounts in the same hour.",
    status: "open",
    related_user: "sara@gmail.com",
    related_order: "ORD-011",
    created_at: "15 Apr 2026, 07:55",
    suggested_action: "Verify device trust, compare order patterns, and escalate if abuse is suspected.",
    timeline: [
      { label: "Shared IP reused by 4 accounts", time: "07:33" },
      { label: "Anomaly score crossed the high severity threshold", time: "07:49" },
      { label: "Flag queued for investigation", time: "07:55" },
    ],
  },
  {
    id: "FLAG-104",
    rule_code: "RETURN-REPEAT-03",
    severity: "medium",
    reason: "Repeated return requests were submitted by the same customer within a short period.",
    status: "escalated",
    related_user: "sara@gmail.com",
    related_order: "ORD-007",
    created_at: "14 Apr 2026, 16:20",
    suggested_action: "Check return history and confirm item condition before approving another return.",
    timeline: [
      { label: "Third return request submitted this month", time: "16:02" },
      { label: "Return behavior rule triggered", time: "16:12" },
      { label: "Case escalated to admin lead", time: "16:20" },
    ],
  },
  {
    id: "FLAG-105",
    rule_code: "LOGIN-ODD-HOUR-04",
    severity: "low",
    reason: "Unusual login activity detected outside the admin's common access window.",
    status: "resolved",
    related_user: "admin@careofyou.id",
    related_order: "-",
    created_at: "14 Apr 2026, 05:54",
    suggested_action: "No action needed if the device is recognized and OTP was verified successfully.",
    timeline: [
      { label: "Login happened outside normal hours", time: "05:48" },
      { label: "OTP challenge completed successfully", time: "05:51" },
      { label: "Flag resolved automatically by admin", time: "05:54" },
    ],
  },
];

export const ADMIN_AUDIT_LOGS = [
  {
    id: "AUD-301",
    action_type: "login success",
    actor: "Admin",
    timestamp: "15 Apr 2026, 08:41",
    result_status: "success",
    ip_address: "36.77.120.45",
  },
  {
    id: "AUD-302",
    action_type: "login failed",
    actor: "Admin",
    timestamp: "15 Apr 2026, 09:03",
    result_status: "failed",
    ip_address: "114.5.33.21",
  },
  {
    id: "AUD-303",
    action_type: "login failed",
    actor: "Admin",
    timestamp: "15 Apr 2026, 09:05",
    result_status: "failed",
    ip_address: "114.5.33.21",
  },
  {
    id: "AUD-304",
    action_type: "suspicious login detected",
    actor: "Monitoring Engine",
    timestamp: "15 Apr 2026, 09:08",
    result_status: "warning",
    ip_address: "114.5.33.21",
  },
  {
    id: "AUD-305",
    action_type: "otp verified",
    actor: "Admin",
    timestamp: "15 Apr 2026, 09:18",
    result_status: "success",
    ip_address: "36.77.120.45",
  },
  {
    id: "AUD-306",
    action_type: "payment approved",
    actor: "Admin",
    timestamp: "15 Apr 2026, 09:18",
    result_status: "success",
    ip_address: "36.77.120.45",
  },
  {
    id: "AUD-307",
    action_type: "payment rejected",
    actor: "Admin",
    timestamp: "14 Apr 2026, 17:42",
    result_status: "warning",
    ip_address: "36.80.74.10",
  },
  {
    id: "AUD-308",
    action_type: "return approved",
    actor: "Admin",
    timestamp: "14 Apr 2026, 16:28",
    result_status: "success",
    ip_address: "36.77.120.45",
  },
  {
    id: "AUD-309",
    action_type: "monitoring flag created",
    actor: "Monitoring Engine",
    timestamp: "14 Apr 2026, 16:20",
    result_status: "warning",
    ip_address: "system",
  },
  {
    id: "AUD-310",
    action_type: "monitoring flag resolved",
    actor: "Admin",
    timestamp: "14 Apr 2026, 05:54",
    result_status: "success",
    ip_address: "36.77.120.45",
  },
];
